# Generated by Django 3.2 on 2021-07-19 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='admin',
            field=models.ManyToManyField(limit_choices_to={'is_admin': True}, to=settings.AUTH_USER_MODEL),
        ),
    ]
