# Generated by Django 3.2 on 2021-07-19 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_auto_20210719_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='admin',
            field=models.ManyToManyField(limit_choices_to={'userprofile.is_admin': True}, to=settings.AUTH_USER_MODEL),
        ),
    ]
