# Generated by Django 3.2 on 2021-07-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userprofile_user'),
        ('board', '0005_alter_post_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='admin',
            field=models.ManyToManyField(limit_choices_to={'is_admin': True}, to='account.UserProfile'),
        ),
    ]
